#ifndef TASK_SETTINGS_H
#define TASK_SETTINGS_H

// Shared FreeRTOS task defaults for this component.
#define TASK_STACK_SIZE_DEFAULT 4096
#define TASK_PRIORITY_DEFAULT 5
#define TASK_CORE_ID_DEFAULT 0

// Main application task settings
#define MAIN_TASK_STACK_SIZE TASK_STACK_SIZE_DEFAULT
#define MAIN_TASK_PRIORITY TASK_PRIORITY_DEFAULT
#define MAIN_TASK_CORE_ID TASK_CORE_ID_DEFAULT

// WiFi application task settings
#define WIFI_APP_TASK_STACK_SIZE TASK_STACK_SIZE_DEFAULT
#define WIFI_APP_TASK_PRIORITY TASK_PRIORITY_DEFAULT
#define WIFI_APP_TASK_CORE_ID TASK_CORE_ID_DEFAULT

// Sensor cache task settings
#define SENSOR_TASK_STACK_SIZE TASK_STACK_SIZE_DEFAULT
#define SENSOR_TASK_PRIORITY (TASK_PRIORITY_DEFAULT + 3)
#define SENSOR_TASK_CORE_ID 1

#endif // TASK_SETTINGS_H